# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Убираем device_tracker из YAML - добавим через UI
# device_tracker:
#   - platform: ping
#     count: 3
#     hosts:
#       phone1: 192.168.1.211
#       laptop1: 192.168.1.184

# Samsung TV integration was removed, use Samsung Smart TV instead
# Configure through UI: Settings -> Devices & Services -> Add Integration -> Samsung Smart TV